### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [lmore377/lmore377#1]
I'm Sorry about where i am trying to communicate with u, but i have a thing to say.
I looked a Github Gist where  u help making Car Thing(Spotify) Usable.
Can we make a project togheter?
I'm learning about WebDev and i think that i can make a web player for spotify, and you just try to figure out how to make it appear instead of the original app.
All in all, it will be an app that looks exactly like the original one, but that can't brick. 😊🫰🏻
(I'm SOOOOOOOOOOOOOOOOO Sorry about my bad english, cuz I'm Brazilian.)

**Comment by lmore377** [comment]
Hello! I'd recommend going to the [Car-Thing-Hax-Community](https://github.com/Car-Thing-Hax-Community/) page and joining the Discord there. There's a bunch of people working on similar projects with the Car Thing.
